name: Make sure new PRs are sent to development

on:
  pull_request_target:
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Vankka/pr-target-branch-action@v1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target: main
          exclude: development # Don't prevent going from development -> main
          change-to: development
          comment: |
              Your PR was set to `main`, PRs should be sent to `development`
              The base branch of this PR has been automatically changed to `development`, please check that there are no merge conflicts
